version: "3.9"

services:
  genesis:
    build: ./genesis
    ports:
      - "8000:8000"
    depends_on:
      - flowmind

  flowmind:
    build: ./flowmind
    ports:
      - "8001:8001"
    env_file:
      - .env
